name: Test
on:
  push:
    branches:
      - station1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependecires
        run: |
          yarn install
      - name: Run Linter Test
        run: |
          npx htmlhint "src/*.html"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn lite-server -c ./bs-config.json
          spec: cypress/integration/station1.spec.js